<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-PO3T4V3" failures="3" tests="4" name="testCases.LoginPopUpTest" time="0.973" errors="0" timestamp="2022-07-19T16:16:26 AMT">
  <testcase classname="testCases.API1_GameLaunch" name="codTest" time="0.042"/>
  <testcase classname="testCases.API1_GameLaunch" name="responseCodeTest" time="0.007">
    <failure type="java.lang.AssertionError" message="expected [0] but found [21]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [21]
at testCases.API1_GameLaunch.responseCodeTest(API1_GameLaunch.java:75)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- responseCodeTest -->
  <testcase classname="testCases.API1_GameLaunch" name="responseDescriptionTest" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [null] but found [{&amp;quot;ClientNotFound&amp;quot;:22,&amp;quot;Description&amp;quot;:&amp;quot;User Not Found&amp;quot;}]">
      <![CDATA[java.lang.AssertionError: expected [null] but found [{"ClientNotFound":22,"Description":"User Not Found"}]
at testCases.API1_GameLaunch.responseDescriptionTest(API1_GameLaunch.java:83)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- responseDescriptionTest -->
  <testcase classname="testCases.API1_GameLaunch" name="responseObjectTest" time="0.002">
    <failure type="java.lang.AssertionError" message="did not expect [null] but found [null]">
      <![CDATA[java.lang.AssertionError: did not expect [null] but found [null]
at testCases.API1_GameLaunch.responseObjectTest(API1_GameLaunch.java:91)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- responseObjectTest -->
</testsuite> <!-- testCases.LoginPopUpTest -->
